[package]
name = "libcrochess"
version = "0.1.0"
authors = ["Mario MlaÄak <mmlacak@gmail.com>"]
edition = "2018"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
