[package]
name = "crochess"
version = "0.1.0"
authors = ["Mario MlaÄak <mmlacak@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libcrochess = { path = "../libcrochess" } # from a path in the local filesystem
